name: 'Deploy API & Backend'

on:
  workflow_dispatch:
    inputs:
      with_backend:
        description: 'Deploy backend (PocketBase)?'
        type: boolean
        required: false
        default: false

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy civ-api to Dokku
        uses: dokku/github-action@master
        with:
          branch: 'main'
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@dokku.civmods.com/civ-api'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy-backend:
    runs-on: ubuntu-latest
    if: inputs.with_backend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy civ-backend to Dokku
        uses: dokku/github-action@master
        with:
          branch: 'main'
          git_push_flags: '--force'
          git_remote_url: 'ssh://dokku@dokku.civmods.com/civ-backend'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
